            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v4.6.0
              with:
                name: artifact
                path: ./build
                if-no-files-found: warn
                retention-days: 30
                compression-level: 6
                overwrite: true
                include-hidden-files: true
